image:                                node:10

pipelines:
  default:
    - step:
        caches:
          - node
        name:                          "Build and Test"
        script:
          - echo "Build, Test and Upload"
          - apt-get update
          - apt-get install jq
          - npm install
          - npm run-script test:unit
          - npm run-script lint
  branches:
    master:
      - step:
          caches:
          - node
          name:                        "Build, Test and Upload"
          script:
            # PACKAGE INSTALLATIONS
            - echo "Build, Test and Upload"
            - apt-get update
            - apt-get install jq zip -y
            - npm install
            - npm run-script test:unit
            - npm run-script build
            - declare -x VERSION=$(jq -r '.version' package.json)
            - echo "$VERSION"
            - zip -r application.zip .
            - pipe:                    atlassian/aws-elasticbeanstalk-deploy:0.5.5
              variables:
                AWS_ACCESS_KEY_ID:     $AWS_ACCESS_KEY_ID
                AWS_SECRET_ACCESS_KEY: $AWS_SECRET_ACCESS_KEY
                AWS_DEFAULT_REGION:    $AWS_DEFAULT_REGION
                APPLICATION_NAME:      '$APPLICATION_NAME'
                COMMAND:               'upload-only'
                ZIP_FILE:              'application.zip'
                VERSION_LABEL:         '$APPLICATION_NAME-$VERSION-$BITBUCKET_BUILD_NUMBER'
      - step:
          name:                        "Deploy to Staging"
          deployment:                  staging
          script:
          - echo "$VERSION Deployment to Staging!"
          - apt-get update
          - apt-get install jq -y
          - declare -x VERSION=$(jq -r '.version' package.json)
          - pipe:                      atlassian/aws-elasticbeanstalk-deploy:0.5.5
            variables:
              AWS_ACCESS_KEY_ID:       $AWS_ACCESS_KEY_ID
              AWS_SECRET_ACCESS_KEY:   $AWS_SECRET_ACCESS_KEY
              AWS_DEFAULT_REGION:      $AWS_DEFAULT_REGION
              APPLICATION_NAME:        '$APPLICATION_NAME'
              COMMAND:                 'deploy-only'
              VERSION_LABEL:           '$APPLICATION_NAME-$VERSION-$BITBUCKET_BUILD_NUMBER'
              ENVIRONMENT_NAME:        '$APPLICATION_NAME-staging'
              WAIT:                    'true'
      - step:
          name:                        "Deploy to Production"
          deployment:                  production
          trigger:                     manual
          script:
            - echo "Deployment to Production!"
            - apt-get update
            - apt-get install jq -y
            - declare -x VERSION=$(jq -r '.version' package.json)
            - pipe:                    atlassian/aws-elasticbeanstalk-deploy:0.5.5
              variables:
                AWS_ACCESS_KEY_ID:     $AWS_ACCESS_KEY_ID
                AWS_SECRET_ACCESS_KEY: $AWS_SECRET_ACCESS_KEY
                AWS_DEFAULT_REGION:    $AWS_DEFAULT_REGION
                APPLICATION_NAME:      '$APPLICATION_NAME'
                COMMAND:               'deploy-only'
                VERSION_LABEL:         '$APPLICATION_NAME-$VERSION-$BITBUCKET_BUILD_NUMBER'
                ENVIRONMENT_NAME:      '$APPLICATION_NAME-production'
                WAIT:                  'true'
