export const GET_CURRENT_NETWORK = "GET_CURRENT_NETWORK";
export const INIT_APP = "INIT_APP";
export const CREATE_LIQUIDITY_RESERVE = "CREATE_LIQUIDITY_RESERVE";
export const LOAD_LIQUIDITY_RESERVE = "LOAD_LIQUIDITY_RESERVE";
export const CLOSE_MINING_DIALOG = "CLOSE_MINING_DIALOG";