// SmartContract
export const GET_CURRENT_NETWORK = "GET_CURRENT_NETWORK";
export const INIT_APP = "INIT_APP";
export const APPROVE_TOKEN_DEPOSIT = "APPROVE_TOKEN_DEPOSIT";
export const CREATE_LIQUIDITY_RESERVE = "CREATE_LIQUIDITY_RESERVE";
export const LOAD_PROVIDER_LIQUIDITY_RESERVES = "LOAD_PROVIDER_LIQUIDITY_RESERVES";
export const LOAD_TOKEN_LIQUIDITY_RESERVES = "LOAD_TOKEN_LIQUIDITY_RESERVES";
export const GET_RESERVE_DETAILS = "GET_RESERVE_DETAILS";
export const CLAIM_LIQUIDITY_RESERVE = "CLAIM_LIQUIDITY_RESERVE";
export const DEPOSIT_TOKEN_LIQUIDITY = "DEPOSIT_TOKEN_LIQUIDITY";
export const DEPOSIT_ETH_LIQUIDITY = "DEPOSIT_ETH_LIQUIDITY";
export const GET_TOKEN_BALANCE = "GET_TOKEN_BALANCE";
export const CLOSE_MINING_DIALOG = "CLOSE_MINING_DIALOG";
export const GET_PRICE_COIN = "GET_PRICE_COIN";